UPDATE countries SET name = 'Afghanistan' where code = 'af';
UPDATE countries SET name = 'Aland Islands' where code = 'ax';
UPDATE countries SET name = 'Albania' where code = 'al';
UPDATE countries SET name = 'Algeria' where code = 'dz';
UPDATE countries SET name = 'American Samoa' where code = 'as';
UPDATE countries SET name = 'Andorra' where code = 'ad';
UPDATE countries SET name = 'Angola' where code = 'ao';
UPDATE countries SET name = 'Anguilla' where code = 'ai';
UPDATE countries SET name = 'Antarctica' where code = 'aq';
UPDATE countries SET name = 'Antigua And Barbuda' where code = 'ag';
UPDATE countries SET name = 'Argentina' where code = 'ar';
UPDATE countries SET name = 'Armenia' where code = 'am';
UPDATE countries SET name = 'Aruba' where code = 'aw';
UPDATE countries SET name = 'Australia' where code = 'au';
UPDATE countries SET name = 'Austria' where code = 'at';
UPDATE countries SET name = 'Azerbaijan' where code = 'az';
UPDATE countries SET name = 'Bahamas' where code = 'bs';
UPDATE countries SET name = 'Bahrain' where code = 'bh';
UPDATE countries SET name = 'Bangladesh' where code = 'bd';
UPDATE countries SET name = 'Barbados' where code = 'bb';
UPDATE countries SET name = 'Belarus' where code = 'by';
UPDATE countries SET name = 'Belgium' where code = 'be';
UPDATE countries SET name = 'Belize' where code = 'bz';
UPDATE countries SET name = 'Benin' where code = 'bj';
UPDATE countries SET name = 'Bermuda' where code = 'bm';
UPDATE countries SET name = 'Bhutan' where code = 'bt';
UPDATE countries SET name = 'Bolivia' where code = 'bo';
UPDATE countries SET name = 'Bosnia And Herzegovina' where code = 'ba';
UPDATE countries SET name = 'Botswana' where code = 'bw';
UPDATE countries SET name = 'Bouvet Island' where code = 'bv';
UPDATE countries SET name = 'Brazil' where code = 'br';
UPDATE countries SET name = 'British Indian Ocean Territory' where code = 'io';
UPDATE countries SET name = 'Brunei Darussalam' where code = 'bn';
UPDATE countries SET name = 'Bulgaria' where code = 'bg';
UPDATE countries SET name = 'Burkina Faso' where code = 'bf';
UPDATE countries SET name = 'Burundi' where code = 'bi';
UPDATE countries SET name = 'Cambodia' where code = 'kh';
UPDATE countries SET name = 'Cameroon' where code = 'cm';
UPDATE countries SET name = 'Canada' where code = 'ca';
UPDATE countries SET name = 'Cape Verde' where code = 'cv';
UPDATE countries SET name = 'Cayman Islands' where code = 'ky';
UPDATE countries SET name = 'Central African Republic' where code = 'cf';
UPDATE countries SET name = 'Chad' where code = 'td';
UPDATE countries SET name = 'Chile' where code = 'cl';
UPDATE countries SET name = 'China' where code = 'cn';
UPDATE countries SET name = 'Christmas Island' where code = 'cx';
UPDATE countries SET name = 'Cocos (Keeling) Islands' where code = 'cc';
UPDATE countries SET name = 'Colombia' where code = 'co';
UPDATE countries SET name = 'Comoros' where code = 'km';
UPDATE countries SET name = 'Congo' where code = 'cg';
UPDATE countries SET name = 'Congo, Democratic Republic' where code = 'cd';
UPDATE countries SET name = 'Cook Islands' where code = 'ck';
UPDATE countries SET name = 'Costa Rica' where code = 'cr';
UPDATE countries SET name = 'Cote D"Ivoire' where code = 'ci';
UPDATE countries SET name = 'Croatia' where code = 'hr';
UPDATE countries SET name = 'Cuba' where code = 'cu';
UPDATE countries SET name = 'Cyprus' where code = 'cy';
UPDATE countries SET name = 'Czech Republic' where code = 'cz';
UPDATE countries SET name = 'Denmark' where code = 'dk';
UPDATE countries SET name = 'Djibouti' where code = 'dj';
UPDATE countries SET name = 'Dominica' where code = 'dm';
UPDATE countries SET name = 'Dominican Republic' where code = 'do';
UPDATE countries SET name = 'Ecuador' where code = 'ec';
UPDATE countries SET name = 'Egypt' where code = 'eg';
UPDATE countries SET name = 'El Salvador' where code = 'sv';
UPDATE countries SET name = 'Equatorial Guinea' where code = 'gq';
UPDATE countries SET name = 'Eritrea' where code = 'er';
UPDATE countries SET name = 'Estonia' where code = 'ee';
UPDATE countries SET name = 'Ethiopia' where code = 'et';
UPDATE countries SET name = 'Falkland Islands (Malvinas)' where code = 'fk';
UPDATE countries SET name = 'Faroe Islands' where code = 'fo';
UPDATE countries SET name = 'Fiji' where code = 'fj';
UPDATE countries SET name = 'Finland' where code = 'fi';
UPDATE countries SET name = 'France' where code = 'fr';
UPDATE countries SET name = 'French Guiana' where code = 'gf';
UPDATE countries SET name = 'French Polynesia' where code = 'pf';
UPDATE countries SET name = 'French Southern Territories' where code = 'tf';
UPDATE countries SET name = 'Gabon' where code = 'ga';
UPDATE countries SET name = 'Gambia' where code = 'gm';
UPDATE countries SET name = 'Georgia' where code = 'ge';
UPDATE countries SET name = 'Germany' where code = 'de';
UPDATE countries SET name = 'Ghana' where code = 'gh';
UPDATE countries SET name = 'Gibraltar' where code = 'gi';
UPDATE countries SET name = 'Greece' where code = 'gr';
UPDATE countries SET name = 'Greenland' where code = 'gl';
UPDATE countries SET name = 'Grenada' where code = 'gd';
UPDATE countries SET name = 'Guadeloupe' where code = 'gp';
UPDATE countries SET name = 'Guam' where code = 'gu';
UPDATE countries SET name = 'Guatemala' where code = 'gt';
UPDATE countries SET name = 'Guernsey' where code = 'gg';
UPDATE countries SET name = 'Guinea' where code = 'gn';
UPDATE countries SET name = 'Guinea-Bissau' where code = 'gw';
UPDATE countries SET name = 'Guyana' where code = 'gy';
UPDATE countries SET name = 'Haiti' where code = 'ht';
UPDATE countries SET name = 'Heard Island & Mcdonald Islands' where code = 'hm';
UPDATE countries SET name = 'Holy See (Vatican City State)' where code = 'va';
UPDATE countries SET name = 'Honduras' where code = 'hn';
UPDATE countries SET name = 'Hong Kong' where code = 'hk';
UPDATE countries SET name = 'Hungary' where code = 'hu';
UPDATE countries SET name = 'Iceland' where code = 'is';
UPDATE countries SET name = 'India' where code = 'in';
UPDATE countries SET name = 'Indonesia' where code = 'id';
UPDATE countries SET name = 'Iran, Islamic Republic Of' where code = 'ir';
UPDATE countries SET name = 'Iraq' where code = 'iq';
UPDATE countries SET name = 'Ireland' where code = 'ie';
UPDATE countries SET name = 'Isle Of Man' where code = 'im';
UPDATE countries SET name = 'Israel' where code = 'il';
UPDATE countries SET name = 'Italy' where code = 'it';
UPDATE countries SET name = 'Jamaica' where code = 'jm';
UPDATE countries SET name = 'Japan' where code = 'jp';
UPDATE countries SET name = 'Jersey' where code = 'je';
UPDATE countries SET name = 'Jordan' where code = 'jo';
UPDATE countries SET name = 'Kazakhstan' where code = 'kz';
UPDATE countries SET name = 'Kenya' where code = 'ke';
UPDATE countries SET name = 'Kiribati' where code = 'ki';
UPDATE countries SET name = 'Korea' where code = 'kr';
UPDATE countries SET name = 'Kuwait' where code = 'kw';
UPDATE countries SET name = 'Kyrgyzstan' where code = 'kg';
UPDATE countries SET name = 'Lao People"s Democratic Republic' where code = 'la';
UPDATE countries SET name = 'Latvia' where code = 'lv';
UPDATE countries SET name = 'Lebanon' where code = 'lb';
UPDATE countries SET name = 'Lesotho' where code = 'ls';
UPDATE countries SET name = 'Liberia' where code = 'lr';
UPDATE countries SET name = 'Libyan Arab Jamahiriya' where code = 'ly';
UPDATE countries SET name = 'Liechtenstein' where code = 'li';
UPDATE countries SET name = 'Lithuania' where code = 'lt';
UPDATE countries SET name = 'Luxembourg' where code = 'lu';
UPDATE countries SET name = 'Macao' where code = 'mo';
UPDATE countries SET name = 'Macedonia' where code = 'mk';
UPDATE countries SET name = 'Madagascar' where code = 'mg';
UPDATE countries SET name = 'Malawi' where code = 'mw';
UPDATE countries SET name = 'Malaysia' where code = 'my';
UPDATE countries SET name = 'Maldives' where code = 'mv';
UPDATE countries SET name = 'Mali' where code = 'ml';
UPDATE countries SET name = 'Malta' where code = 'mt';
UPDATE countries SET name = 'Marshall Islands' where code = 'mh';
UPDATE countries SET name = 'Martinique' where code = 'mq';
UPDATE countries SET name = 'Mauritania' where code = 'mr';
UPDATE countries SET name = 'Mauritius' where code = 'mu';
UPDATE countries SET name = 'Mayotte' where code = 'yt';
UPDATE countries SET name = 'Mexico' where code = 'mx';
UPDATE countries SET name = 'Micronesia, Federated States Of' where code = 'fm';
UPDATE countries SET name = 'Moldova' where code = 'md';
UPDATE countries SET name = 'Monaco' where code = 'mc';
UPDATE countries SET name = 'Mongolia' where code = 'mn';
UPDATE countries SET name = 'Montenegro' where code = 'me';
UPDATE countries SET name = 'Montserrat' where code = 'ms';
UPDATE countries SET name = 'Morocco' where code = 'ma';
UPDATE countries SET name = 'Mozambique' where code = 'mz';
UPDATE countries SET name = 'Myanmar' where code = 'mm';
UPDATE countries SET name = 'Namibia' where code = 'na';
UPDATE countries SET name = 'Nauru' where code = 'nr';
UPDATE countries SET name = 'Nepal' where code = 'np';
UPDATE countries SET name = 'Netherlands' where code = 'nl';
UPDATE countries SET name = 'Netherlands Antilles' where code = 'an';
UPDATE countries SET name = 'New Caledonia' where code = 'nc';
UPDATE countries SET name = 'New Zealand' where code = 'nz';
UPDATE countries SET name = 'Nicaragua' where code = 'ni';
UPDATE countries SET name = 'Niger' where code = 'ne';
UPDATE countries SET name = 'Nigeria' where code = 'ng';
UPDATE countries SET name = 'Niue' where code = 'nu';
UPDATE countries SET name = 'Norfolk Island' where code = 'nf';
UPDATE countries SET name = 'Northern Mariana Islands' where code = 'mp';
UPDATE countries SET name = 'Norway' where code = 'no';
UPDATE countries SET name = 'Oman' where code = 'om';
UPDATE countries SET name = 'Pakistan' where code = 'pk';
UPDATE countries SET name = 'Palau' where code = 'pw';
UPDATE countries SET name = 'Palestinian Territory, Occupied' where code = 'ps';
UPDATE countries SET name = 'Panama' where code = 'pa';
UPDATE countries SET name = 'Papua New Guinea' where code = 'pg';
UPDATE countries SET name = 'Paraguay' where code = 'py';
UPDATE countries SET name = 'Peru' where code = 'pe';
UPDATE countries SET name = 'Philippines' where code = 'ph';
UPDATE countries SET name = 'Pitcairn' where code = 'pn';
UPDATE countries SET name = 'Poland' where code = 'pl';
UPDATE countries SET name = 'Portugal' where code = 'pt';
UPDATE countries SET name = 'Puerto Rico' where code = 'pr';
UPDATE countries SET name = 'Qatar' where code = 'qa';
UPDATE countries SET name = 'Reunion' where code = 're';
UPDATE countries SET name = 'Romania' where code = 'ro';
UPDATE countries SET name = 'Russian Federation' where code = 'ru';
UPDATE countries SET name = 'Rwanda' where code = 'rw';
UPDATE countries SET name = 'Saint Barthelemy' where code = 'bl';
UPDATE countries SET name = 'Saint Helena' where code = 'sh';
UPDATE countries SET name = 'Saint Kitts And Nevis' where code = 'kn';
UPDATE countries SET name = 'Saint Lucia' where code = 'lc';
UPDATE countries SET name = 'Saint Martin' where code = 'mf';
UPDATE countries SET name = 'Saint Pierre And Miquelon' where code = 'pm';
UPDATE countries SET name = 'Saint Vincent And Grenadines' where code = 'vc';
UPDATE countries SET name = 'Samoa' where code = 'ws';
UPDATE countries SET name = 'San Marino' where code = 'sm';
UPDATE countries SET name = 'Sao Tome And Principe' where code = 'st';
UPDATE countries SET name = 'Saudi Arabia' where code = 'sa';
UPDATE countries SET name = 'Senegal' where code = 'sn';
UPDATE countries SET name = 'Serbia' where code = 'rs';
UPDATE countries SET name = 'Seychelles' where code = 'sc';
UPDATE countries SET name = 'Sierra Leone' where code = 'sl';
UPDATE countries SET name = 'Singapore' where code = 'sg';
UPDATE countries SET name = 'Slovakia' where code = 'sk';
UPDATE countries SET name = 'Slovenia' where code = 'si';
UPDATE countries SET name = 'Solomon Islands' where code = 'sb';
UPDATE countries SET name = 'Somalia' where code = 'so';
UPDATE countries SET name = 'South Africa' where code = 'za';
UPDATE countries SET name = 'South Georgia And Sandwich Isl.' where code = 'gs';
UPDATE countries SET name = 'Spain' where code = 'es';
UPDATE countries SET name = 'Sri Lanka' where code = 'lk';
UPDATE countries SET name = 'Sudan' where code = 'sd';
UPDATE countries SET name = 'Suriname' where code = 'sr';
UPDATE countries SET name = 'Svalbard And Jan Mayen' where code = 'sj';
UPDATE countries SET name = 'Swaziland' where code = 'sz';
UPDATE countries SET name = 'Sweden' where code = 'se';
UPDATE countries SET name = 'Switzerland' where code = 'ch';
UPDATE countries SET name = 'Syrian Arab Republic' where code = 'sy';
UPDATE countries SET name = 'Taiwan' where code = 'tw';
UPDATE countries SET name = 'Tajikistan' where code = 'tj';
UPDATE countries SET name = 'Tanzania' where code = 'tz';
UPDATE countries SET name = 'Thailand' where code = 'th';
UPDATE countries SET name = 'Timor-Leste' where code = 'tl';
UPDATE countries SET name = 'Togo' where code = 'tg';
UPDATE countries SET name = 'Tokelau' where code = 'tk';
UPDATE countries SET name = 'Tonga' where code = 'to';
UPDATE countries SET name = 'Trinidad And Tobago' where code = 'tt';
UPDATE countries SET name = 'Tunisia' where code = 'tn';
UPDATE countries SET name = 'Turkey' where code = 'tr';
UPDATE countries SET name = 'Turkmenistan' where code = 'tm';
UPDATE countries SET name = 'Turks And Caicos Islands' where code = 'tc';
UPDATE countries SET name = 'Tuvalu' where code = 'tv';
UPDATE countries SET name = 'Uganda' where code = 'ug';
UPDATE countries SET name = 'Ukraine' where code = 'ua';
UPDATE countries SET name = 'United Arab Emirates' where code = 'ae';
UPDATE countries SET name = 'United Kingdom' where code = 'gb';
UPDATE countries SET name = 'United States' where code = 'us';
UPDATE countries SET name = 'United States Outlying Islands' where code = 'um';
UPDATE countries SET name = 'Uruguay' where code = 'uy';
UPDATE countries SET name = 'Uzbekistan' where code = 'uz';
UPDATE countries SET name = 'Vanuatu' where code = 'vu';
UPDATE countries SET name = 'Venezuela' where code = 've';
UPDATE countries SET name = 'Vietnam' where code = 'vn';
UPDATE countries SET name = 'Virgin Islands, British' where code = 'vg';
UPDATE countries SET name = 'Virgin Islands, U.S.' where code = 'vi';
UPDATE countries SET name = 'Wallis And Futuna' where code = 'wf';
UPDATE countries SET name = 'Western Sahara' where code = 'eh';
UPDATE countries SET name = 'Yemen' where code = 'ye';
UPDATE countries SET name = 'Zambia' where code = 'zm';
UPDATE countries SET name = 'Zimbabwe' where code = 'zw';
